apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ingress
  name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ingress
    spec:
      containers:
      - image: reverseproxy
        name: ingress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ingress
  name: ingress
spec:
  ports:
  - name: frontend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ingress
  type: LoadBalancer
status:
  loadBalancer: {}