apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: ashokjjk/react-f
        name: react-f
        ports:
        - containerPort: 3001
        env:
        - name: REACT_APP_BACK_API
          value: http://localhost:30007/api
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: frontend
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}