apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: ashokjjk/react-f
        name: react-f
        ports:
        - containerPort: 3001
        env:
        - name: REACT_APP_BACK_API
          value: http://localhost:3000/api
        resources: {}
status: {}